### ISSUE TITLE
Yang Viewer NoClassDefFoundError

### ISSUE THREAD

**Issue by ds2286s** [YangModels/yang#78]
I have built the yangviewer-project.
**But it seems like there is missing a class in the repository.**
I can build the jar with the pom.xml

But when i run  "java -jar yang-viewer-1.0.0-SNAPSHOT-jar-with-dependencies.jar" it fails.

Exception in thread "main" java.lang.NoClassDefFoundError: org/opendaylight/yang
tools/yang/model/parser/api/YangContextParser
        at org.brocade.yangviewer.Main.createJTree(Main.java:123)
        at org.brocade.yangviewer.Main.main(Main.java:91)
Caused by: java.lang.ClassNotFoundException: org.opendaylight.yangtools.yang.mod
el.parser.api.YangContextParser
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 2 more

**Comment by ds2286s** [comment]
Solved it. I need to add the dependent jars to the classpath
